### ISSUE TITLE
Indepently verify pip installation

### ISSUE THREAD

**Issue by paddymul** [buckaroo-data/buckaroo#15]
@kolibril13 would you mind giving this a try?

I just renamed my project again and would like confirmation that it installs properly.
https://buckaroo-data.readthedocs.io/en/latest/ 
What do the docs and initial experience seem like to you?

Thanks

**Comment by kolibril13** [comment]
I did:
jan-hendrik@JanHendriksAir okapi % python3.11 -m venv .venv
jan-hendrik@JanHendriksAir okapi % source .venv/bin/activate
(.venv) jan-hendrik@JanHendriksAir okapi % pip install buckaroo
(.venv) jan-hendrik@JanHendriksAir okapi % pip install pandas
(.venv) jan-hendrik@JanHendriksAir okapi % python -m pip install jupyterlab
(.venv) jan-hendrik@JanHendriksAir okapi % python -m jupyterlab       
And it works out of the box in JupyterLab

```
import pandas as pd

# get a pandas dataframe from the web

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv')
from buckaroo.buckaroo_widget import BuckarooWidget
BuckarooWidget(df=df)  #df being the dataframe you want to explore
```
<img width="948" alt="image" src="https://user-images.githubusercontent.com/44469195/236274592-b0a4a27c-cf3c-47d5-9364-652f39217dd0.png">

In VS Code I get an error:
![image](https://user-images.githubusercontent.com/44469195/236274051-1c662980-54c4-425a-b667-da4c71ae45cc.png)

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'DCEFWidgetModel' from module 'buckaroo'
Error: No version of module buckaroo is registered
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)
    at ph.loadModelClass (https://file+.vscode-resource.vscode-cdn.net/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)
    at ph._make_model (https://file+.vscode-resource.vscode-cdn.net/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
    at ph.new_model (https://file+.vscode-resource.vscode-cdn.net/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)
    at ph.handle_comm_open (https://file+.vscode-resource.vscode-cdn.net/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)
    at https://file+.vscode-resource.vscode-cdn.net/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511
    at g._handleCommOpen (https://file+.vscode-resource.vscode-cdn.net/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-arm64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:2:36493)
    at async g._handleMessage (https://file+.vscode-resource.vscode-cdn.net/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-arm64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:2:38387)
````

**Comment by kolibril13** [comment]
> What do the docs and initial experience seem like to you?

Cool project, I think this can be very useful!
The UI feels a bit clunky, but the logic is great.

The docs are great, but are missing an example, I'd say.
Maybe it's worth thinking of adding a interactive demo with jupyterlite/binder.
https://github.com/scikit-hep/awkward/blob/main/docs/getting-started/try-awkward-array.md
JupyterLite actually has a sphinx directive that you can try here:
https://awkward-array.org/doc/main/getting-started/try-awkward-array.html
https://github.com/scikit-hep/awkward/blob/main/docs/getting-started/try-awkward-array.md

**Comment by paddymul** [comment]
Thank You!!!

How would you improve the clunkiness of the UI?

Is it a styling issue or interaction design issue?

I know the styling needs help.


The biggest missing feature for new users is no error messages when
Operations are setup in an invalid order.  That's worth adding.

I'm figuring out when to publicize this.  There are always features to add,
but most projects fail because they fail to get adoption.

Paddy
